version: "3.5"
services:
  backend:
    build: backend
    ports:
    - "3001:3001"
    - "8083:8083"
    - "8889:8889/udp"
    - "8001:8001/udp"
    - "8890:8890/udp"
    - "11111:11111/udp"
  cockpit:
    build: frontends/cockpit
    depends_on:
    - video-stream
    - control-center
    - telemetry-stream
    ports:
    - "80:3000"
  video-stream:
    build: frontends/video-stream
    depends_on:
    - backend
    ports:
    - "8080:8080"
  control-center:
    build: frontends/control-center
    depends_on:
    - backend
    ports:
    - "8081:8081"
  telemetry-stream:
    build: frontends/telemetry-stream
    depends_on:
    - backend
    ports:
    - "8082:8082"