version: "3.5"
services:
  # frontend client development live-reload (watch) server
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - "./frontend:/usr/src/app"
    - "/usr/src/app/node_modules"
  # backend server development live-reload (watch) server
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3001:3001"
      - "8083:8083"
      - "8889:8889/udp"
      - "8001:8001/udp"
      - "8890:8890/udp"
      - "11111:11111/udp"
