version: "3.5"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
    - "./backend:/usr/src/app"
    - "/usr/src/app/node_modules"
    ports:
    - "3001:3001"
    - "8083:8083"
    - "8889:8889/udp"
    - "8001:8001/udp"
    - "8890:8890/udp"
    - "11111:11111/udp"
  cockpit:
    build:
      context: frontends/cockpit
      dockerfile: Dockerfile.dev
    ports:
    - "80:3000"
    volumes:
    - "./frontends/cockpit:/usr/src/app"
    - "/usr/src/app/node_modules"
  video-stream:
    build:
      context: frontends/video-stream
      dockerfile: Dockerfile.dev
    volumes:
    - "./frontends/video-stream:/usr/src/app"
    - "/usr/src/app/node_modules"
    depends_on:
    - backend
    ports:
    - "8080:8080"
  control-center:
    build:
      context: frontends/control-center
      dockerfile: Dockerfile.dev
    depends_on:
    - backend
    ports:
    - "8081:8081"
    volumes:
    - "./frontends/control-center:/usr/src/app"
    - "/usr/src/app/node_modules"
  telemetry-stream:
    build:
      context: frontends/telemetry-stream
      dockerfile: Dockerfile.dev
    depends_on:
    - backend
    ports:
    - "8082:8082"
    volumes:
    - "./frontends/telemetry-stream:/usr/src/app"
    - "/usr/src/app/node_modules"
